=== mqnc/kite-motion-planner/docs/scene.schema.json
{
	"$schema": "https://json-schema.org/draft/t2020-12/schema",
	"$ref": "#/$defs/Scene",

	"$defs": {

		"Scene": {
			"type": "object",
			"properties": {
				"models": {
					"type": "object",
					"patternProperties": {
						"": { "$ref": "#/$defs/Model" }
					}
				},
				"objects": {
					"type": "object",
					"patternProperties": {
						"": { "$ref": "#/$defs/Object" }
					}
				},
				"collisionIgnoreGroups": {
					"type": "object",
					"patternProperties": {
						"": {
							"type": "array",
							"items": { "type": "string" }
						}
					}
				},
				"trajectories": {
					"type": "object",
					"patternProperties": {
						"": { "$ref": "#/$defs/Trajectory" }
					}
				}
			},
			"additionalProperties": false
		},


		"Model": {
			"properties": {
				"kind": { "type": "string" }
			},
			"oneOf": [
				{ "$ref": "#/$defs/RobotModel" },
				{ "$ref": "#/$defs/RigidBodyModel" }
			],
			"required": [ "kind" ]
		},


		"Object": {
			"type": "object",
			"properties": {
				"model": { "type": "string" },
				"parent": { "type": "string", "default": "WORLD" },
				"pose": { "$ref": "#/$defs/Trafo" },
				"jointValues": {
					"type": "object",
					"patternProperties": {
						"": { "$ref": "#/$defs/Value" }
					}
				}
			},
			"required": [ "model", "parent" ],
			"additionalProperties": false
		},


		"RobotModel": {
			"type": "object",
			"properties": {
				"kind": { "const": "robot" },
				"links": {
					"type": "object",
					"patternProperties": {
						"": { "$ref": "#/$defs/Link" }
					}
				},
				"partModels": {
					"type": "object",
					"patternProperties": {
						"": { "$ref": "#/$defs/RigidBodyModel" }
					}
				},
				"joints": {
					"type": "object",
					"patternProperties": {
						"": { "$ref": "#/$defs/Joint" }
					}
				},
				"collisionIgnoreGroups": {
					"type": "object",
					"patternProperties": {
						"": {
							"type": "array",
							"items": { "type": "string" }
						}
					}
				},
				"constraints": {
					"type": "object",
					"patternProperties": {
						"": {
							"type": "object",
							"patternProperties": {
								"": { "type": "number" }
							}
						}
					}
				},
				"visuals": { "type": "string" }
			},
			"required": [ "links" ],
			"additionalProperties": false
		},


		"Joint": {
			"type": "object",
			"properties": {
				"minValue": { "type": "number" },
				"maxValue": { "type": "number" },
				"maxVelocity": { "type": "number" },
				"maxAcceleration": { "type": "number" },
				"maxDeceleration": { "type": "number" },
				"maxJerk": { "type": "number" },
				"maxEffort": { "type": "number" }
			},
			"additionalProperties": false
		},


		"Link": {
			"type": "object",
			"properties": {
				"parent": { "type": "string" },
				"pose": { "$ref": "#/$defs/Trafo" },
				"parts": {
					"type": "array",
					"items": { "type": "string" }
				}
			},
			"required": [ "parent" ],
			"additionalProperties": false
		},


		"RigidBodyModel": {
			"type": "object",
			"properties": {
				"kind": { "const": "rigidBody" },
				"centerOfMass": { "$ref": "#/$defs/Vector3" },
				"mass": { "type": "number", "default": 0 },
				"inertia": {
					"type": "object",
					"properties": {
						"ixx": { "type": "number", "default": 0 },
						"iyy": { "type": "number", "default": 0 },
						"izz": { "type": "number", "default": 0 },
						"ixy": { "type": "number", "default": 0 },
						"ixz": { "type": "number", "default": 0 },
						"iyz": { "type": "number", "default": 0 }
					},
					"additionalProperties": false
				},
				"shapes": {
					"type": "object",
					"patternProperties": {
						"": { "$ref": "#/$defs/Shape" }
					}
				},
				"visuals": { "type": "string" }
			},
			"additionalProperties": false
		},


		"Shape": {
			"oneOf": [
				{ "$ref": "#/$defs/Sphere" },
				{ "$ref": "#/$defs/Box" },
				{ "$ref": "#/$defs/Cylinder" },
				{ "$ref": "#/$defs/OrangeNet" },
				{ "$ref": "#/$defs/Mesh" }
			],
			"properties": {
				"margin": { "type": "number" },
				"collides": { "type": "boolean", "default": true },
				"stickyForce": { "type": "number" },
				"visuals": { "type": "object" }
			},
			"unevaluatedProperties": false
		},


		"Sphere": {
			"type": "object",
			"properties": {
				"kind": { "const": "sphere" },
				"center": { "$ref": "#/$defs/Vector3" },
				"radius": { "kind": "number" }
			},
			"required": [ "kind", "radius" ]
		},


		"Box": {
			"type": "object",
			"properties": {
				"kind": { "const": "box" },
				"pose": { "$ref": "#/$defs/Trafo" },
				"size": { "$ref": "#/$defs/Vector3" }
			},
			"required": [ "kind", "size" ]
		},


		"Cylinder": {
			"type": "object",
			"properties": {
				"kind": { "const": "cylinder" },
				"center": { "$ref": "#/$defs/Vector3" },
				"radius": { "type": "number" },
				"height": { "type": "number" },
				"axis": {
					"oneOf": [
						{ "type": "string", "enum": [ "x", "y", "z" ] },
						{ "$ref": "#/$defs/Vector3" }
					]
				}
			},
			"required": [ "kind", "radius", "height", "axis" ]
		},


		"OrangeNet": {
			"type": "object",
			"properties": {
				"kind": { "const": "orangeNet" },
				"points": { "$ref": "#/$defs/Vector3Array" },
				"radius": { "type": "number" }
			},
			"required": [ "kind", "points", "radius" ]
		},


		"Mesh": {
			"type": "object",
			"properties": {
				"kind": { "const": "mesh" },
				"vertices": { "$ref": "#/$defs/Vector3Array" },
				"faces": { "$ref": "#/$defs/UIntVector3Array" }
			},
			"required": [ "kind", "vertices", "faces" ]
		},


		"Trafo": {
			"type": "object",
			"default": { "xyz": [ 0, 0, 0 ], "euler": { "z0y1x2": [ 0, 0, 0 ] } },
			"properties": {
				"xyz": { "$ref": "#/$defs/Values3" },
				"axisDistance": { "$ref": "#/$defs/AxisDistance" },
				"qwxyz": { "$ref": "#/$defs/Quat" },
				"qxyzw": { "$ref": "#/$defs/Quat" },
				"cols3x3": { "$ref": "#/$defs/Matrix3x3" },
				"rows3x3": { "$ref": "#/$defs/Matrix3x3" },
				"cols4x4": { "$ref": "#/$defs/Matrix4x4" },
				"rows4x4": { "$ref": "#/$defs/Matrix4x4" },
				"euler": { "$ref": "#/$defs/Euler" },
				"axisAngle": { "$ref": "#/$defs/AxisAngle" },
				"rotvec": { "$ref": "#/$defs/Values3" },
				"dh": { "$ref": "#/$defs/DH" }
			},
			"oneOf": [
				{ "required": [ "xyz", "qwxyz" ], "maxProperties": 2 },
				{ "required": [ "xyz", "qxyzw" ], "maxProperties": 2 },
				{ "required": [ "xyz", "cols3x3" ], "maxProperties": 2 },
				{ "required": [ "xyz", "rows3x3" ], "maxProperties": 2 },
				{ "required": [ "xyz", "euler" ], "maxProperties": 2 },
				{ "required": [ "xyz", "axisAngle" ], "maxProperties": 2 },
				{ "required": [ "xyz", "rotvec" ], "maxProperties": 2 },
				{ "required": [ "axisDistance", "qwxyz" ], "maxProperties": 2 },
				{ "required": [ "axisDistance", "qxyzw" ], "maxProperties": 2 },
				{ "required": [ "axisDistance", "cols3x3" ], "maxProperties": 2 },
				{ "required": [ "axisDistance", "rows3x3" ], "maxProperties": 2 },
				{ "required": [ "axisDistance", "euler" ], "maxProperties": 2 },
				{ "required": [ "axisDistance", "axisAngle" ], "maxProperties": 2 },
				{ "required": [ "axisDistance", "rotvec" ], "maxProperties": 2 },
				{ "required": [ "cols4x4" ], "maxProperties": 1 },
				{ "required": [ "rows4x4" ], "maxProperties": 1 },
				{ "required": [ "dh" ], "maxProperties": 1 }
			]
		},

		"JointReference": {
			"type": "object",
			"properties": {
				"joint": { "type": "string" }
			},
			"required": [ "joint" ],
			"additionalProperties": false
		},

		"TrajectoryReference": {
			"type": "object",
			"properties": {
				"trajectory": { "type": "string" },
				"index": { "type": "number" }
			},
			"required": [ "trajectory" ],
			"additionalProperties": false
		},

		"Reference": {
			"oneOf": [
				{ "$ref": "#/$defs/JointReference" },
				{ "$ref": "#/$defs/TrajectoryReference" }
			]
		},

		"Value": {
			"oneOf": [
				{ "type": [ "number", "string" ], "default": 0 },
				{ "$ref": "#/$defs/Reference" }
			]
		},

		"Values3": {
			"type": "array",
			"items": { "$ref": "#/$defs/Value" },
			"minItems": 3,
			"maxItems": 3
		},

		"NumberOrVector": {
			"oneOf": [
				{ "type": "number" },
				{ "$ref": "#/$defs/Vector" }
			]
		},

		"Vector": {
			"type": "array",
			"items": { "type": "number" }
		},

		"Vector3": {
			"type": "array",
			"items": { "type": "number", "default": 0 },
			"minItems": 3,
			"maxItems": 3
		},

		"Vector3Array": {
			"type": "array",
			"items": { "$ref": "#/$defs/Vector3" }
		},

		"UIntVector3": {
			"type": "array",
			"items": { "type": "integer", "minimum": 0 },
			"minItems": 3,
			"maxItems": 3
		},

		"UIntVector3Array": {
			"type": "array",
			"items": { "$ref": "#/$defs/UIntVector3" }
		},

		"Vector4": {
			"type": "array",
			"items": { "type": "number" },
			"minItems": 4,
			"maxItems": 4
		},

		"Quat": {
			"oneOf": [
				{ "$ref": "#/$defs/Vector4" },
				{ "type": "string" }
			]
		},

		"Matrix3x3": {
			"type": "array",
			"items": { "$ref": "#/$defs/Vector3" },
			"minItems": 3,
			"maxItems": 3
		},

		"Matrix4x4": {
			"type": "array",
			"items": { "$ref": "#/$defs/Vector4" },
			"minItems": 4,
			"maxItems": 4
		},

		"Euler": {
			"type": "object",
			"properties": {
				"z0x0z0": { "$ref": "#/$defs/Values3" },
				"x0y0x0": { "$ref": "#/$defs/Values3" },
				"y0z0y0": { "$ref": "#/$defs/Values3" },
				"z0y0z0": { "$ref": "#/$defs/Values3" },
				"x0z0x0": { "$ref": "#/$defs/Values3" },
				"y0x0y0": { "$ref": "#/$defs/Values3" },
				"x0y0z0": { "$ref": "#/$defs/Values3" },
				"y0z0x0": { "$ref": "#/$defs/Values3" },
				"z0x0y0": { "$ref": "#/$defs/Values3" },
				"x0z0y0": { "$ref": "#/$defs/Values3" },
				"z0y0x0": { "$ref": "#/$defs/Values3" },
				"y0x0z0": { "$ref": "#/$defs/Values3" },
				"z0x1z2": { "$ref": "#/$defs/Values3" },
				"x0y1x2": { "$ref": "#/$defs/Values3" },
				"y0z1y2": { "$ref": "#/$defs/Values3" },
				"z0y1z2": { "$ref": "#/$defs/Values3" },
				"x0z1x2": { "$ref": "#/$defs/Values3" },
				"y0x1y2": { "$ref": "#/$defs/Values3" },
				"x0y1z2": { "$ref": "#/$defs/Values3" },
				"y0z1x2": { "$ref": "#/$defs/Values3" },
				"z0x1y2": { "$ref": "#/$defs/Values3" },
				"x0z1y2": { "$ref": "#/$defs/Values3" },
				"z0y1x2": { "$ref": "#/$defs/Values3" },
				"y0x1z2": { "$ref": "#/$defs/Values3" }
			},
			"minProperties": 1,
			"maxProperties": 1,
			"additionalProperties": false
		},

		"AxisDistance": {
			"type": "object",
			"properties": {
				"axis": { "$ref": "#/$defs/Vector3" },
				"distance": { "$ref": "#/$defs/Value" }
			},
			"required": [ "axis", "distance" ],
			"additionalProperties": false
		},

		"AxisAngle": {
			"type": "object",
			"properties": {
				"axis": { "$ref": "#/$defs/Vector3" },
				"angle": { "$ref": "#/$defs/Value" }
			},
			"required": [ "axis", "angle" ],
			"additionalProperties": false
		},

		"DH": {
			"type": "object",
			"properties": {
				"a": { "$ref": "#/$defs/Value" },
				"alpha": { "$ref": "#/$defs/Value" },
				"theta": { "$ref": "#/$defs/Value" },
				"s": { "$ref": "#/$defs/Value" }
			},
			"required": [ "a", "alpha", "theta", "s" ],
			"additionalProperties": false
		},

		"Trajectory": {
			"type": "object",
			"properties": {
				"controlPoints": {
					"type": "array",
					"items": { "$ref": "#/$defs/ControlPoint" }
				},
				"dtDefault": { "type": "number", "default": 1.0 },
				"repeat": { "$ref": "#/$defs/Repetition" }
			},
			"required": [ "controlPoints" ],
			"additionalProperties": false
		},

		"ControlPoint": {
			"type": "object",
			"properties": {
				"t": { "type": "number" },
				"dt": { "type": "number" },
				"f": { "$ref": "#/$defs/NumberOrVector" },
				"df": { "$ref": "#/$defs/NumberOrVector" },
				"ddf": { "$ref": "#/$defs/NumberOrVector" }
			},
			"oneOf": [
				{ "required": [ "f" ], "not": { "required": [ "dt" ] } },
				{ "required": [ "f" ], "not": { "required": [ "t" ] } }
			],
			"additionalProperties": false
		},

		"Repetition": {
			"oneOf": [
				{ "type": "boolean" },
				{
					"type": "object",
					"properties": {
						"t": { "type": "number" },
						"dt": { "type": "number" }
					},
					"oneOf": [
						{ "required": [ "t" ], "not": { "required": [ "dt" ] } },
						{ "required": [ "dt" ], "not": { "required": [ "t" ] } }
					],
					"additionalProperties": false
				}
			]
		}
	}
}

=== mqnc/kite-motion-planner/scenes/big_test_scene.json
{
	"models": {

		"hodgepodge": {
			"kind": "rigidBody",
			"centerOfMass": [ 1, 2, 3 ],
			"mass": 4,
			"inertia": { "ixx": 5, "iyy": 6, "izz": 7 },
			"shapes": {
				"mySphere": {
					"kind": "sphere",
					"center": [ 1, 2, 3 ],
					"radius": 4
				},
				"myBox": {
					"kind": "box",
					"pose": { "xyz_qxyzw": [ 4, 3, 2, 1, 0, 0, 0 ] },
					"size": [ 7, 6, 5 ]
				},
				"myXCylinder": {
					"kind": "cylinder",
					"center": [ 1, 2, 3 ],
					"radius": 4,
					"height": 5,
					"axis": "x"
				},
				"myYZCylinder": {
					"kind": "cylinder",
					"center": [ 1, 2, 3 ],
					"radius": 4,
					"height": 5,
					"axis": [ 0, 1, 1 ]
				},
				"myOrangeNet": {
					"kind": "orangeNet",
					"points": [ [ 1, 2, 3 ], [ 2, 3, 1 ], [ 3, 1, 2 ] ],
					"radius": 4
				},
				"myTetrahedron": {
					"kind": "mesh",
					"vertices": [ [ -1, -1, -1 ], [ -1, 1, 1 ], [ 1, -1, 1 ], [ 1, 1, -1 ] ],
					"faces": [ [ 0, 1, 2 ], [ 0, 1, 3 ], [ 0, 2, 3 ], [ 1, 2, 3 ] ]
				}
			}
		},

		"myArm": {
			"kind": "robot",
			"links": {
				"base": {
					"parent": "ROOT",
					"pose": { "xyz": [ { "joint": "cartX" }, { "joint": "cartY" }, 0 ], "qxyzw": [ 0, 0, 0, 1 ] }
				},
				"upperArm": {
					"parent": "base",
					"pose": { "dh": { "a": 0, "alpha": 0, "theta": { "joint": "shoulder" }, "s": 1 } },
					"parts": [ "upperArmCylinder" ]
				},
				"foreArm": {
					"parent": "upperArm",
					"pose": { "cols4x4": [ [ 11, 21, 31, 41 ], [ 12, 22, 32, 42 ], [ 13, 23, 33, 43 ], [ 14, 24, 34, 44 ] ] }
				},
				"finger1": {
					"parent": "foreArm",
					"pose": { "dh": { "a": 0, "alpha": 0, "theta": { "joint": "knuckle1" }, "s": 0.1 } },
					"parts": [ "gripperFinger" ]
				},
				"finger2": {
					"parent": "foreArm",
					"pose": { "dh": { "a": 0, "alpha": 0, "theta": { "joint": "knuckle2" }, "s": 0.1 } },
					"parts": [ "gripperFinger" ]
				}
			},
			"partModels": {
				"upperArmCylinder": {
					"shapes": {
						"s1": {
							"kind": "cylinder",
							"center": [ 0.5, 0, 0 ],
							"radius": 0.05,
							"height": 1,
							"axis": "x"
						}
					}
				},
				"gripperFinger": {
					"shapes": {
						"fingerShape": {
							"kind": "cylinder",
							"center": [ 0, 0.1, 0 ],
							"radius": 0.01,
							"height": 0.23,
							"axis": "y",
							"stickyForce": 5
						}
					}
				}
			},
			"joints": {
				"cartX": { },
				"cartY": { },
				"shoulder": { },
				"elbow": {
					"minValue": -3.14,
					"maxValue": 3.14,
					"maxVelocity": 1,
					"maxAcceleration": 1,
					"maxDeceleration": 5,
					"maxJerk": 10,
					"maxEffort": 10
				},
				"knuckle1": { },
				"knuckle2": { }
			},
			"collisionIgnoreGroups": {
				"arm": [ "upperArm", "foreArm" ],
				"hand": [ "foreArm", "finger1", "finger2" ]
			},
			"constraints": {
				"grip": { "finger1": 1.0, "finger2": -1.0 }
			}
		},

		"mySphere": {
			"kind": "rigidBody",
			"shapes": {
				"sphereShape": {
					"kind": "sphere",
					"center": [ 0, 0, 0 ],
					"radius": 1
				}
			}
		}
	},

	"objects": {
		"myFirstRobot": {
			"model": "myArm",
			"parent": "WORLD",
			"pose": { "xyz_qxyzw": [ 0, 0, 0, 0, 0, 0, 1 ] },
			"jointValues": {
				"shoulder": 0.21,
				"elbow": 0.4
			}
		},
		"mylinkedRobot": {
			"model": "myArm",
			"parent": "myFirstRobot.foreArm",
			"pose": { "xyz_qxyzw": [ 0, 0, 0, 0, 0, 0, 1 ] },
			"jointValues": {
				"shoulder": 0.22,
				"elbow": 0.4
			}
		},
		"myObject1": {
			"parent": "WORLD",
			"pose": { "xyz_qxyzw": [ 4, 3, 2, 1, 0, 0, 0 ] },
			"model": "hodgepodge"
		},
		"myObject2": {
			"parent": "myObject1",
			"pose": { "xyz_qxyzw": [ 4, 3, 2, 1, 0, 0, 0 ] },
			"model": "hodgepodge",
			"todo model": { "file": "file://myExternalFile.json" }
		},
		"movingObstacle1": {
			"parent": "WORLD",
			"pose": { "xyz": [ 0, { "trajectory": "oscillation" }, 5 ], "euler": { "x0z1y2": [ 1, 2, 3 ] } },
			"model": "mySphere"
		},
		"movingObstacle2": {
			"parent": "WORLD",
			"pose": { "xyz": [ 0, { "trajectory": "oscillation" }, 5 ], "euler": { "x0z1y2": [ 1, 2, 3 ] } },
			"pose_": { "xyz_qxyzw": { "trajectory": "wobble" } },
			"model": "mySphere"
		}
	},


	"collisionIgnoreGroups": {
		"touch": [ "myInPlaceObject2.myLocalSphere", "" ]
	},

	"trajectories": {
		"oscillation": {
			"controlPoints": [
				{ "f": 1, "df": 0 },
				{ "f": -1, "df": 0 }
			],
			"dtDefault": 0.5,
			"repeat": true
		},
		"wobble": {
			"controlPoints": [
				{ "t": 0, "f": [ 1, 0, 0, 0, 0, 0, 1 ], "df": [ 0, 0, 0, 0, 0, 0, 0 ] },
				{ "t": 1, "f": [ -1, 0, 0, 0, 0, -1, 0 ], "df": [ 0, 0, 0, 0, 0, 0, 0 ] }
			],
			"dtDefault": 0.0,
			"repeat": true
		}
	}
}
